
os: osx 
language: generic 
before_script: 
 - pip install six
 - brew update 
 - brew install --HEAD libimobiledevice 
 - brew install ideviceinstaller 
 - brew install ios-deploy 
  - install  - ./flutter/bin/flutter doctor
 - git clone https://github.com/flutter/flutter.git -b beta --depth 1 

 script: 
 - flutter/bin/flutter build ios --debug --no-codesign
 cache:
  directories:
    - $HOME/.pub-cache
