os: linux
language: android
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-google_apis-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
jdk: oraclejdk8
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
install:
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo apt-get -y install npm
  - npm install -g firebase-tools
before_script:
  - wget http://services.gradle.org/distributions/gradle-5.2.1-bin.zip
  - unzip -qq gradle-5.2.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.2.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
script:
  - ./flutter/bin/flutter -v build apk
before_install:
    - yes | sdkmanager "platforms;android-27"
cache:
  directories:
    - $HOME/.pub-cache
deploy:
  provider: firebase
  skip_cleanup: true
  token: 
    secure: "X9vwvNb4LSt8ToQNxxwakKkeOYd0fneYgD5CGZAb1FuQAvOcEpyRXkLXrAGT/i1FcN692OMm8Cx98Gt2/0n6qVA4d1lAGr20y18bwqL5OUMzuyixWOn47bGjo637jxm+EkzGAJN+uXTOlcb4MG8r+x8MC/+kyvEWKdBJiQBPnDTkhkh76RuRBDZtPzxT7fANxokulc9RobYYR+ikpLWXUJt4Jy2BbP4UqkSi+8BleHsuOIVVYGFltIKe1r3BMFGVdQhVsyoZuPpsWs1kyRwQX4ABK86gPulboOG4kmUAvIe8wF8FiI37htmndNMKwB5JROFS8+3JzarQV3LFM2N3a30tHFYzNr01fwduIzokG7rlHlpOWGnMu78FvSQE5FvRIPhJtPZMJlA6wdQjc5l9n3IaQ9UBnBONOt+bL14We9/wsfKJ1w2iO3f8vNE0gkOkqTnQSF7Ea2ciDJlOFZsN+Kylq5/2iTsULnWn/uiSaHDT0HfB6dqk47wkSFUuJ2dgcOL8DaTo2PrNpBTz0G9igBGKnHv09zZSuDSisoA/55Ytyh46HBuVOI3815DtkyeZSMK1v+Vx8foWppjftNIEIJlPkvotTSwkANkHq9enDdlVauZaYmsNjHtl/f/hIDHaKHEdup4mk6saZLLOO9tQWTtGoR+CtuMWvSVfFsBTelw="
  project: "super-awesome-project-de648"
