
before_script: 
  - "pip install six"
  - "brew update"
  - "brew install --HEAD libimobiledevice"
  - "brew install ideviceinstaller"
  - "brew install ios-deploy"
  - "git clone https://github.com/flutter/flutter.git -b alpha --depth 1"
  - "install - ./flutter/bin/flutter doctor"
cache: 
  directories: 
    - $HOME/.pub-cache
language: generic
os: osx
script: 
  - "./flutter/bin/flutter -v build ios --no-codesign"
